Docker:that runs applications inside container 

how to install docker

sudo apt update

sudo apt install docker.io -y(engine installed)

sudo systemctl start docker
sudo systemctl enable docker(service started and enabled)

for version

docker --version

docker ps

test and run docker

docker run hello-world
 
To create container

mkdir c_container

vim hello.c
 
vim Dockerfile

FROM gcc:latest
WORKDIR /app
COPY hello.c .
RUN gcc hello.c -o hello
CMD ["./hello"]

compilation steps:

build the docker image 
docker build -t c-hello .

run container
docker run c-hello




